schema_version: 1
name: os-jws-prometheus
version: '3.0'
description: Prometheus for JWS
execute:
- script: run

ports:
    - value: 9404
      protocol: tcp
      description: internal port for prometheus agent

envs:
- name: JBOSS_CONTAINER_PROMETHEUS_MODULE
  value: /opt/jboss/container/prometheus
- name: AB_PROMETHEUS_ENABLE
  description: Enable the use of the Prometheus agent
  value: true
- name: AB_PROMETHEUS_JMX_EXPORTER_PORT
  description: Port to use for the Prometheus JMX Exporter.
  value: 9404
- name: AB_PROMETHEUS_JMX_EXPORTER_CONFIG
  value: /opt/jboss/container/prometheus/etc/jws-jmx-exporter-config.yaml
  description: Path to configuration to use for the Prometheus JWS JMX Exporter
