#!/bin/sh
# Prometheus JMX for JWS
set -e

SCRIPT_DIR=$(dirname $0)
ADDED_DIR="$SCRIPT_DIR/added"

# install prometheus-jmx-exporter
dnf install -y prometheus-jmx-exporter
if ! $(ls -la /etc/alternatives/java |grep -q "java-1\.8\.0"); then
    if [ -n "$(yum list installed java-1.8.0-openjdk-devel |grep java-1.8.0-openjdk-devel)" ]; then
        rpm -e --nodeps java-11-openjdk-headless prometheus-jmx-exporter-openjdk1
    fi
fi
dnf clean all

# copy the configuration for JWS
mkdir -p /opt/jboss/container/prometheus/etc
cp -p "$ADDED_DIR/jws-jmx-exporter-config.yaml" /opt/jboss/container/prometheus/etc/jws-jmx-exporter-config.yaml
cp -p "$ADDED_DIR/prometheus-opts" /opt/jboss/container/prometheus/jws-prometheus-opts
